language: c
compiler:
    - gcc
    - clang
before_install: sudo apt-get update
install: sudo apt-get install simh
script: ${CC} -g -O3 -Wall -Werror -o primes primes.c && ./primes | diff - primes-ref && sh ./primes.sh > primes-pdp-out && diff primes-pdp-out primes-ref
